# trials/errors.py
class ParticipantAlreadyInTrial(Exception):
    pass

class SlotAlreadyTaken(Exception):
    pass